# Generated by Django 4.2.2 on 2023-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_cash', models.IntegerField(null=True)),
                ('minus_cash', models.IntegerField(null=True)),
                ('total_cash', models.IntegerField(null=True)),
                ('explain', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('designate_date', models.DateField()),
            ],
        ),
    ]
