# Generated by Django 4.2.2 on 2023-08-16 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_cash', models.IntegerField(null=True)),
                ('minus_cash', models.IntegerField(null=True)),
                ('total_cash', models.IntegerField(null=True)),
                ('explain', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('designate_date', models.DateField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
