# Generated by Django 4.2.2 on 2023-08-13 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
