# Generated by Django 4.2.2 on 2023-08-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractbaseuser',
            name='kakao_check',
            field=models.IntegerField(null=True),
        ),
    ]
